info.version: @project.version@
management:
  context-path: /sysadmin
  port: 8142
  security:
    enabled: false
server:
  context-path: /nlfp-public
  port: 8042

spring:
  application:
    name: NlfpPublic
  boot:
    admin:
      # boot-admin is run by status-server project; if not running a warning will be emitted
      url: http://localhost:9999/boot-admin
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    servlet:
      # We don't want to wait for initial request to initialize the servlet:
      load-on-startup: 1

jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}

environment: local

### Everything above this line is for the default Spring profile.
### Everything below this line is for specific Spring profiles / overrides for different environments.

---

spring:
  profiles: dev
  boot:
    admin:
      url:

environment: development

---
spring:
  profiles: test
  boot:
    admin:
      url:

environment: test


---
spring:
  profiles: prod
  boot:
    admin:
      url:

environment: prod
